### ISSUE TITLE
v0.3.4 - submatrix causes segmentation fault on invalid input

### ISSUE THREAD

**Issue by jgegenfurtner** [Daniel-Diaz/matrix#15]
Hello,

[submatrix](http://hackage.haskell.org/package/matrix-0.3.4.0/docs/Data-Matrix.html#v:submatrix) causes a Segmentation Fault on invalid input, i.e. 0 as 'Starting Row', 0 as 'Starting Column', (x > nrows m) as 'Ending Row' or (x > ncols m) as 'Ending Col'.

Minimal crashing example:
----------------------------------
>import Data.Matrix  
m :: Matrix Int
m = fromList 4 4 [1..]  
noCrash :: Matrix Int
noCrash = submatrix 1 4 1 4 m  
crash0 :: Matrix Int
crash0 = submatrix 0 4 0 4 m  
crash1 :: Matrix Int
crash1 = submatrix 1 5 1 5 m

Output:
> $ ghci
GHCi, version 7.6.3: http://www.haskell.org/ghc/  :? for help
Loading package ghc-prim ... linking ... done.
Loading package integer-gmp ... linking ... done.
Loading package base ... linking ... done.
Prelude> :l crash
[1 of 1] Compiling Main             ( crash.hs, interpreted )
Ok, modules loaded: Main.
*Main> noCrash
Loading package array-0.4.0.1 ... linking ... done.
Loading package deepseq-1.3.0.1 ... linking ... done.
Loading package loop-0.2.0 ... linking ... done.
Loading package primitive-0.5.4.0 ... linking ... done.
Loading package vector-0.10.12.1 ... linking ... done.
Loading package matrix-0.3.4.0 ... linking ... done.
(  1  2  3  4 )
(  5  6  7  8 )
(  9 10 11 12 )
( 13 14 15 16 )
*Main> crash0
( 8603456 35942470297157632 Segmentation fault

> $ ghci
GHCi, version 7.6.3: http://www.haskell.org/ghc/  :? for help
Loading package ghc-prim ... linking ... done.
Loading package integer-gmp ... linking ... done.
Loading package base ... linking ... done.
Prelude> :l crash
[1 of 1] Compiling Main             ( crash.hs, interpreted )
Ok, modules loaded: Main.
*Main> noCrash
Loading package array-0.4.0.1 ... linking ... done.
Loading package deepseq-1.3.0.1 ... linking ... done.
Loading package loop-0.2.0 ... linking ... done.
Loading package primitive-0.5.4.0 ... linking ... done.
Loading package vector-0.10.12.1 ... linking ... done.
Loading package matrix-0.3.4.0 ... linking ... done.
(  1  2  3  4 )
(  5  6  7  8 )
(  9 10 11 12 )
( 13 14 15 16 )
*Main> crash1
(  1  2  3  4  5 )
(  5  6  7  8  9 )
(  9 10 11 12 13 )
( 13 14 15 16 Segmentation fault

Here are my specs:
> $ uname -a
Linux c3p1 3.16.0-4-amd64 #1 SMP Debian 3.16.7-2 (2014-11-06) x86_64 GNU/Linux
$ ghci --version
The Glorious Glasgow Haskell Compilation System, version 7.6.3
$ cabal info matrix | grep "Versions installed"
    Versions installed: 0.3.4.0

Btw, this also crashed on Windows using WinGHCi.

**Comment by Daniel-Diaz** [comment]
``submatrix`` no longer accepts invalid arguments. See https://github.com/Daniel-Diaz/matrix/commit/7bdb702d69efcf3a6467c8dfd0e7a78226f80bcc.

Thanks.
