### ISSUE TITLE
Missing Applicative instance 

### ISSUE THREAD

**Issue by Jefffrey** [Daniel-Diaz/matrix#17]
Sounds like a `Matrix a` is a perfect fit for an `Applicative` (and possibly even `Monad`) instance. `Data.Vector` also [has such instances](http://hackage.haskell.org/package/vector-0.10.12.2/docs/Data-Vector.html), and given that the former is implemented in terms of the latter, the actual implementation of these instances should be trivial.

What am I missing?

**Comment by octopuscabbage** [comment]
Applicative I can see, although it would have to be a partial function because it will only work on matricies of the same dimensions. 

I don't see a monad instance because how would one concatenate matricies in a sane way.

**Comment by hherman1** [comment]
I'd say >> ~ Tensor Product,

As far as concatenation

Monoid a => Monoid (Matrix a)
Pointwise mappend

**Comment by octopuscabbage** [comment]
I'd say >> ~ Tensor Product,

I'm not familiar with that operation so I can't really say if that makes sense or not.

Monoid a => Monoid (Matrix a)
Pointwise mappend

makes sense, for different sized matrices we could just  <> mempty.

**Comment by hherman1** [comment]
http://www.sharetechnote.com/image/EngMath_TensorProduct_01.png

Similar to how list does >>, but makes sense in 2D

**Comment by octopuscabbage** [comment]
What happens if the matrices are differently sized? Would they just be mempty?

**Comment by octopuscabbage** [comment]
I plan to at least write the monoid instance in a few minutes and the tensor product if I can figure it out.

**Comment by hherman1** [comment]
its a_ii * B, dimensions dont matter for tensor

**Comment by octopuscabbage** [comment]
ohh i see that now

**Comment by octopuscabbage** [comment]
The problem being that applicative is a requirement for monad.  Maybe we can work backwards from <*> being ap?

**Comment by octopuscabbage** [comment]
would applicative just be tensor multiplication but instead of multiplication be function application?

**Comment by Jefffrey** [comment]
I guess we can close this now, right?

**Comment by octopuscabbage** [comment]
I suppose once the PR gets merged but we should probably take our commentary there.

**Comment by Daniel-Diaz** [comment]
Closing this. See https://github.com/Daniel-Diaz/matrix/pull/27
