### ISSUE TITLE
Missing: inverse function

### ISSUE THREAD

**Issue by kavigupta** [Daniel-Diaz/matrix#24]
I was trying to use this library for some simple computations, but there is no matrix inverse function.

This seems like a pretty basic function to have in a Matrix library.

I would like to use a pure Haskell solution to avoid having to install C++ libraries, but this missing feature makes Matrix basically unusable for me.

**Comment by Daniel-Diaz** [comment]
It's true, an ``inverse`` function is basic and required. I'll try to write one as soon as possible. Contributions are welcome too! :)

**Comment by kavigupta** [comment]
I'm willing to contribute this to the repository.

**Comment by octopuscabbage** [comment]
I'd be willing to work on this if someone gave me a good reference implementation to work from as I slept through a lot of linear algebra.

**Comment by kavigupta** [comment]
I submitted a patch a few weeks ago. It probably wasn't beautiful code, but
it got the job done. If you would like to clean it up and resubmit, I'll
forward it to you

**Comment by kavigupta** [comment]
Since my pull request was merged, I'm going to close this issue.

**Comment by Daniel-Diaz** [comment]
Thanks!
