### ISSUE TITLE
Exception from Reduced Row Echelon Form Conversion

### ISSUE THREAD

**Issue by Tuplanolla** [Daniel-Diaz/matrix#52]
The following expression throws an exception
when it should return a `Left` value.

    > rref (matrix 2 3 (fromIntegral . uncurry (*)))
    Right ( *** Exception: getElem: Trying to get the (2,1) element from a 1x2 matrix.

**Comment by wchresta** [comment]
This seems fixed with the newest version

**Comment by Tuplanolla** [comment]
Right you are.
Jolly good work.
